version: "3.7"

services:
    # image project
    app:
        container_name: tasks
        build:
            context: .
            dockerfile: Dockerfile
        image: tasks/tasks-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - tasks-net

    # nginx
    nginx:
        container_name: tasks-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - tasks-net

    # db mysql
    mysql:
        container_name: tasks-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            #MYSQL_DATABASE: ${DB_DATABASE}
            #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            #MYSQL_PASSWORD: ${DB_PASSWORD}
            #MYSQL_USER: ${DB_USERNAME}
            MYSQL_DATABASE: "julianomonteiro_tasks"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_PASSWORD: "secret"
            MYSQL_USER: "root"
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - tasks-net

    # queue
    queue:
        container_name: tasks-queue
        image: tasks/tasks-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - tasks-net

    # redis
    redis:
        container_name: tasks-redis
        image: redis:latest
        networks:
            - tasks-net

networks:
    tasks-net:
        driver: bridge